### ISSUE TITLE
Inaccurate Contributing Guidelines

### ISSUE THREAD

**Issue by AlainODea** [joyent/sdcboot#4]
I want to fix this. I'm not annoyed, just concerned that contributions to this project are getting lost and interested in collaborating toward a solution :)

## Problem
There is no Gerrit Code Review project, but the contributor guidelines linked in README.md suggest that it is required. As a hopeful contributor here, I feel discouraged and confused, but I'm motivated to resolve this.

## Motivation
My Pull Requests (#1, #3 have gotten little to no attention). I thought that I must be doing something wrong, so I reviewed the contributor's guide linked in the README.md and immediately realized my error: I need to create CRs through Gerrit Code Review at https://cr.joyent.us/.

So, I created a cr.joyent.us account and added a remote to my working copy for CRs and went to push my changes there. I discovered that the joyent/sdcboot project doesn't exist in Gerrit.

I was back to square one. I have pull requests that probably won't be accepted, and a standard contribution process that can't be satisfied without changes to Gerrit.

## Suggested Fix
Add **CONTRIBUTING.md** with either:
* a clear, concise description along the lines of GitHub's own recommendations:
https://github.com/blog/1184-contributing-guidelines
* OR a link to the Triton contributing guidelines and the addition of a Gerrit project for joyent/sdcboot

**Comment by AlainODea** [comment]
@jclulow does this make sense?

**Comment by jclulow** [comment]
Hi.  Sorry about that.  I've imported the project into Gerrit, and we'll work on bringing the `README` into line with other Triton projects.

**Comment by AlainODea** [comment]
Woohoo! Thank you!
